<?php
// $Id$

/**
 * @file
 *
 * Provide integration with Google Chrome Frame
 */

/**
 * Implements hook_menu().
 */
function chrome_frame_menu() {
  $items = array();
  $items['admin/settings/chrome_frame'] = array(
    'title' => 'Chrome Frame',
    'description' => 'Configure Chrome Frame Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chrome_frame_settings'),
    'access arguments' => array('administer site configuration')
  );
  return $items;
}

/**
 * Administer Module Settings
 */
function chrome_frame_settings() {
  $form = array();
  return system_settings_form($form);
}

/**
 * Implements hook_init().
 *
 * Add the chrome meta tag, and all the javascript
 */
function chrome_frame_init() {
  drupal_set_html_head('<meta http-equiv="X-UA-Compatible" content="chrome=1">');
}

/**
 * Implements hook_footer().
 */
function chrome_frame_footer($main = 0) {
  return '
<div id="chrome_frame"></div>
<script src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js" type="text/javascript"></script>
<script type="text/javascript">
    CFInstall.check({
      node: "chrome_frame"
    });
</script>';
}