<?php
// $Id$

/**
 * @file
 *
 * Provide integration with Google Chrome Frame
 */

/**
 * Implements hook_menu().
 */
function chrome_frame_menu() {
  $items = array();
  $items['admin/settings/chrome_frame'] = array(
    'title' => 'Chrome Frame',
    'description' => 'Configure Chrome Frame Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chrome_frame_settings'),
    'access arguments' => array('administer site configuration')
  );
  return $items;
}

/**
 * Administer Module Settings
 */
function chrome_frame_settings() {
  $form = array();
  $form['chrome_frame_prompt'] = array(
    '#title' => t('Prompt the user to install Chrome Frame?'),
    '#type' => 'radios',
    '#options' => array(
      0 => t('Don\'t Prompt'),
      1 => t('IE 6 only'),
      2 => t('Prompt for all versions of IE')
    ),
    '#default_value' => variable_get('chrome_frame_prompt', 0),
  );
  $form['chrome_frame_mode'] = array(
    '#title' => t('Mode'),
    '#type' => 'select',
    '#options' => array(
      'inline' => t('Inline'),
      'popup' => t('Popup'),
    ),
    '#description' => t('How the user should be prompted when Google Chrome Frame is missing. Using a Popup will result in creating a new window for the prompt.'),
    '#default_value' => variable_get('chrome_frame_mode', 'inline'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_init().
 *
 * Add the chrome meta tag, and all the javascript
 */
function chrome_frame_init() {
  drupal_set_html_head('<meta http-equiv="X-UA-Compatible" content="chrome=1" />');
}

/**
 * Implements hook_footer().
 */
function chrome_frame_footer($main = 0) {
  // Construct the options passed to the CFInstall check function.
  $options = drupal_to_js(array(
    'node' => 'chrome-frame',
    'mode' => variable_get('chrome_frame_mode', 'inline'),
  ));

  switch (variable_get('chrome_frame_prompt', 0)) {
    case 2:
      // Always prompt.
      return '<div id="chrome-frame"></div>
<script src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js" type="text/javascript"></script>
<script type="text/javascript">
    CFInstall.check('. $options .');
</script>';
      break;
    case 1:
      // Prompt only for IE 6.
      return '<div id="chrome-frame"></div>
<!--[if lte IE 6]>
<script src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js" type="text/javascript"></script>
<script type="text/javascript">
    CFInstall.check('. $options .');
</script>
<![endif]-->';
      break;
    case 0:
      // Don't prompt to install plugin.
      break;
  }
  
}